---
title: "Multiple-Linear-Regression-Correction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Multiple-Linear-Regression-Correction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


First the package should be loaded:
```{r setup}
library(aws.wrfsmn)
```

The example data to use will be 'eva':
```{r, echo = FALSE, results = FALSE}
data(eva)
```

```{r}
head(eva)
```

A Multiple Linear Regression is made between the predictand (observed evaporation) and the following predictors:
```{r}
test.predictors <- c('OUT_PREC',
                     'OUT_EVAP',
                     'OUT_RUNOFF',
                     'OUT_BASEFLOW',
                     'OUT_SOIL_MOIST_lyr_1',
                     'OUT_EVAP_CANOP',
                     'OUT_SURF_TEMP')
```

Using multiple.guidance function:
```{r}
mg <- multiple.guidance(input.data = eva, predictand = 'evapo_obs', predictors = test.predictors)
mg
```

The evaluation of this correction is:
```{r}
evaluation.eva <- mg.evaluation(input.data = eva, predictand = 'evapo_obs', predictors = test.predictors, var.model = 'OUT_EVAP', lmodel = mg)

evaluation.eva
```

Finally, the monthly data is calculated to be plot:
```{r}
ploting(daily2monthly(evaluation.eva[[1]]))
```
